server:
  port: 8081

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/test
      client:
        registration:
          keycloak:
            client-id: testclient
            client-secret: pFoyqhV09KElNpckaMe1KkAwSNysP09R
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/test
            user-name-attribute: preferred_username
application:
  keycloak:
    server-url: http://localhost:8080
    realm: test
    username: john123
    password: john123
    client-id: testclient
    client-secret: pFoyqhV09KElNpckaMe1KkAwSNysP09R
    token-url: http://localhost:8080/realms/test/protocol/openid-connect/token

#logging:
#  level:
#    com.msauth.msauthkeycloak: trace
#    web: trace
#    root: trace

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

jwt:
  auth:
    converter:
      resource-id: testclient
